Pract.03 01 - 02 | Teodora Tsaneva
Justsvetoslavov/Object-oriented_programming_FMI pull request #114
Opened 2023-03-18 17:10 UTC by tedy11

Teodora Tsaneva
IS 4 5MI0700155

2023-03-20 16:10 UTC, Nedko-Nedev requested changes

2023-03-20 16:10 UTC, Nedko-Nedev commented on Seminars/Sem.03/Pract.03/Task01.cpp
> +    brown,
По конвенция имената на enum елементите са capital case.

2023-03-20 16:10 UTC, Nedko-Nedev commented on Seminars/Sem.03/Pract.03/Task01.cpp
> +    } while (student.fn < 10000 && student.fn < 9999);
Прегледай си пак условието в while-a.

2023-03-20 16:10 UTC, Nedko-Nedev commented on Seminars/Sem.03/Pract.03/Task01.cpp
> +    } while (studentsCount < 1 && studentsCount > 1024);
Провери си условието в while-a.

2023-03-20 16:10 UTC, Nedko-Nedev commented on Seminars/Sem.03/Pract.03/Task01.cpp
> +    file << "Name: " << student.name << ", " << endl;
Не трябва да имаш допълнителен текст в csv файла, освен < value1 > , < value2 > , ... , < valuen >

2023-03-20 16:10 UTC, Nedko-Nedev commented on Seminars/Sem.03/Pract.03/Task01.cpp
> +    case HairColor::brown:file << "brown"; break;
Хубаво е да имаш default случай.

2023-03-20 16:10 UTC, Nedko-Nedev commented on Seminars/Sem.03/Pract.03/Task01.cpp
> +    string MyStr(enum_string[val]);
Още не използваме string.

2023-03-20 16:10 UTC, Nedko-Nedev commented on Seminars/Sem.03/Pract.03/Task01.cpp
> +    if (system.count <= MAX_STUDENT)
Строго неравенство.

2023-03-20 16:10 UTC, Nedko-Nedev commented on Seminars/Sem.03/Pract.03/Task02.cpp
> +    file.write((const char*)&jobAd.projectCompletionBonus, sizeof(long long));
Не си затворила файла.

2023-03-20 16:10 UTC, Nedko-Nedev commented on Seminars/Sem.03/Pract.03/Task02.cpp
> +    file.write(jobAd.companyName, sizeof(char) * MAX_SIZE);
Може да ползваш sizeof(jobAd.companyName) за по-лесно.

2023-03-20 16:10 UTC, Nedko-Nedev commented on Seminars/Sem.03/Pract.03/Task02.cpp
> +void PrintJobOffer(JobAd jobAd)
Ползвай копие.

2023-03-20 16:10 UTC, Nedko-Nedev commented on Seminars/Sem.03/Pract.03/Task02.cpp
> +    while (file.read(jobAd.companyName, sizeof(char) * MAX_SIZE) &&
Можеш да прочетеш и да запишеш цяла структура, няма нужда поле по поле. Size-ът ти е sizeof(JobAd).

2023-03-20 16:10 UTC, Nedko-Nedev commented on Seminars/Sem.03/Pract.03/Task02.cpp
> +    cout << "Enter command(0 - to add offers" << endl;
Добре е да се направи логиката с въвеждане на командите в цикъл. Потребителят въвежда повече от 1 команди с едно пускане на програмата. Да стане като потребителски интерфейс.

2023-03-24 19:14 UTC, Justsvetoslavov commented
@Nedko-Nedev Seems like everything was addressed. Just a confirmation, please.

2023-03-25 22:57 UTC, closed without merging