Pract.03: Add 01-03 | Borislav Gunovski
Justsvetoslavov/Object-oriented_programming_FMI pull request #115
Opened 2023-03-19 20:17 UTC by IHaveNoIdeaWhatImDo-ing

Borislav Gunovski
4 1MI0700119

2023-03-20 16:51 UTC, Nedko-Nedev requested changes

2023-03-20 16:51 UTC, Nedko-Nedev commented on Seminars/Sem.03/Pract.03/Task01.cpp
> +using namespace std;
Избягвай използването на целия namespace.

2023-03-20 16:51 UTC, Nedko-Nedev commented on Seminars/Sem.03/Pract.03/Task01.cpp
> +    Brown, Black, Blond, Red, White
По конвенция имената на enum елементите са с главни букви само.

2023-03-20 16:51 UTC, Nedko-Nedev commented on Seminars/Sem.03/Pract.03/Task01.cpp
> +        muchenitsi[index++].hair = (Hair)temp;
Идеята е в и от файла да се чете и пише цвета на косата като символен низ, не като символ.

2023-03-20 16:51 UTC, Nedko-Nedev commented on Seminars/Sem.03/Pract.03/Task02.cpp
> +        streamReader.read((char*)&tempoffer.name       , sizeof(tempoffer.name));
Можеш да прочетеш цялата структура, не елемент по елемент.

2023-03-20 16:51 UTC, Nedko-Nedev commented on Seminars/Sem.03/Pract.03/Task02.cpp
> +        if (tempname == name)
Как сравняваме низове за равенство?

2023-03-20 16:51 UTC, Nedko-Nedev commented on Seminars/Sem.03/Pract.03/Task02.cpp
> +    readOffersConsole();
Къде работиш с потребителския интерфейс, описан в условието?

2023-03-20 16:51 UTC, Nedko-Nedev commented on Seminars/Sem.03/Pract.03/Task03.cpp
> +    if (streamWriter.is_open())
Ползвай скоби дори и за едноредовките, подобрява четимостта.

2023-03-20 16:51 UTC, Nedko-Nedev commented on Seminars/Sem.03/Pract.03/Task03.cpp
> +    return 0;
Демонстрирай работа с написаните функции.

2023-03-24 19:15 UTC, Justsvetoslavov commented on Seminars/Sem.03/Pract.03/Task01.cpp
> +using namespace std;
Избягвай и std::cin, std::cout, std::endl, std::ofstream, std::ifstream, наистина не е толкова приятно , колкото повече колеги си мислят.

2023-03-24 19:15 UTC, closed without merging