Pract.04: Added Task02 | Boyan Vidolov
Justsvetoslavov/Object-oriented_programming_FMI pull request #130
Opened 2023-03-23 17:49 UTC by boyan1742

Boyan Vidolov
SI 5
1MI0600250

2023-03-25 11:18 UTC, Justsvetoslavov commented
Can we rename the files? (remove the Task_)
Wrap them in a folder Task02.

2023-03-25 14:24 UTC, dejansvetoslavov requested changes

2023-03-25 14:24 UTC, dejansvetoslavov commented on Seminars/Sem.04/Pract.04/Task_Task02.h
> +    char m_name[MAX_TASK_NAME_SIZE + 1]{};
Avoid {} initialisation - it works only with VS.

2023-03-25 14:24 UTC, dejansvetoslavov commented on Seminars/Sem.04/Pract.04/Exam_Task02.h
> +    int m_currentTaskPtr = 0;
Avoid Ptr in the name, it might confused for a cpp pointer

2023-03-25 14:24 UTC, dejansvetoslavov commented on Seminars/Sem.04/Pract.04/Exam_Task02.h
> +    Exam(int minPoints = 0);
Create default ctor and avoid default parameter

2023-03-25 14:24 UTC, dejansvetoslavov commented on Seminars/Sem.04/Pract.04/Exam_Task02.cpp
> +void Exam::WriteToFile(std::ofstream &file) const
Don't separate opening a file and the actual writing - pass only the file name

2023-03-25 14:24 UTC, dejansvetoslavov commented on Seminars/Sem.04/Pract.04/Exam_Task02.cpp
> +void Exam::ReadFromFile(std::ifstream &file)
Same as above

2023-03-27 08:55 UTC, boyan1742 commented
I have made the changes that were requested.

2023-03-30 16:49 UTC, merged