Pract.05: Add 01 | Bozhidar Tomov
Justsvetoslavov/Object-oriented_programming_FMI pull request #145
Opened 2023-03-26 13:40 UTC by Bozhidar-Tomov

Bozhidar Tomov
SI 1 0MI0600171

2023-03-27 08:17 UTC, Justsvetoslavov commented
Can you rename task due to added tasks in https://github.com/Justsvetoslavov/Object-oriented_programming_FMI/blob/master/Seminars/Sem.05/Pract.%2005/README.md?

2023-03-27 12:39 UTC, Bozhidar-Tomov commented
I get server error when i try to rename the files. I renamed the PR to the task it belongs to.
before: ~~Pract.05: Add 01 | Bozhidar Tomov~~
new:** Pract.05: Add 02 | Bozhidar Tomov**

2023-04-06 21:36 UTC, Justsvetoslavov requested changes

2023-04-06 21:36 UTC, Justsvetoslavov commented on Seminars/Sem.05/Pract. 05/Task01/Task02.h
> +ComplexNumber add(const ComplexNumber &, const ComplexNumber &);
Shouldn't these 3 be friend functions ? If yes, why?

2023-04-06 21:36 UTC, Justsvetoslavov commented on Seminars/Sem.05/Pract. 05/Task01/Task02.cpp
> +    return x < 0 ? -x : x;
Absolute in doubles, how is it determined?

2023-04-22 12:31 UTC, closed without merging