Pract.06: Add 01-02 | Nikita Beliy
Justsvetoslavov/Object-oriented_programming_FMI pull request #156
Opened 2023-04-04 18:22 UTC by N1k1ta-white

Nikita Beliy
SI 1 9MI800022

2023-04-22 12:34 UTC, Justsvetoslavov commented
@GeorgiTerziev02 @khatoni Can you take a look?

2023-04-24 17:35 UTC, khatoni requested changes
There are some big mistakes

2023-04-24 17:35 UTC, khatoni commented on Deck/Deck.h
> +    Deck& operator=(Deck deck1);
You do not need to overload operator = here

2023-04-24 17:35 UTC, khatoni commented on Duelist/Duelist.h
> +    }
since this class has dynamic memory you need also copy constructor and copy assignment operator=

2023-04-24 17:35 UTC, khatoni commented on Item/Item.h
> +    void copyItem(const Item& item);
make this function private

2023-04-24 17:35 UTC, khatoni commented on Item/Item.h
> +    void delItem();
make this private as well

2023-04-24 17:35 UTC, khatoni commented on Monster/Monster.h
> +
No copy constructor

2023-04-24 17:35 UTC, khatoni commented on Monster/Monster.cpp
> +}
Where is the check if (this!=&other)

2023-04-24 17:35 UTC, khatoni commented on ShoppingCart/ShoppingCart.h
> +
BIG 4 ????

2023-04-24 17:35 UTC, khatoni commented on ShoppingCart/ShoppingCart.cpp
> +    delete[] items;
this is redundant

2023-05-12 20:20 UTC, closed without merging