Pract.07: Add 01 | Bozhidar Tomov
Justsvetoslavov/Object-oriented_programming_FMI pull request #160
Opened 2023-04-10 22:18 UTC by Bozhidar-Tomov

Bozhidar Tomov
SI 1 0MI0600171

2023-04-22 12:37 UTC, Justsvetoslavov commented
@GeorgiTerziev02 @khatoni Can you take a look?

2023-04-24 17:53 UTC, khatoni requested changes

2023-04-24 17:53 UTC, khatoni commented on Seminars/Sem.07/Pract. 07/MyString.cpp
> +MyString::MyString(const char *data) : _data(new char[DEFAULT_CAPACITY]{'\0'}), _capacity(DEFAULT_CAPACITY)
Why do you allocate memory twice, this could be done just once in the body of the constructor

2023-04-24 17:53 UTC, khatoni commented on Seminars/Sem.07/Pract. 07/MyString.cpp
> +int MyString::size() const
this should be size_t the size cannot be negative

2023-04-24 17:53 UTC, khatoni commented on Seminars/Sem.07/Pract. 07/MyString.cpp
> +int MyString::length() const
size_t

2023-04-24 17:53 UTC, khatoni commented on Seminars/Sem.07/Pract. 07/main.cpp
> +}
You do not catch the exceptions

2023-04-24 17:53 UTC, khatoni commented on Seminars/Sem.07/Pract. 07/MyString.cpp
> +    return in >> obj._data;
this works only for the default length of string

2023-04-29 20:31 UTC, closed without merging