Prac07|Add 01
Justsvetoslavov/Object-oriented_programming_FMI pull request #161
Opened 2023-04-12 23:09 UTC by NIkoTod

Todorov Nikolai SI 1 2MI8000043

2023-04-22 12:37 UTC, Justsvetoslavov commented
@GeorgiTerziev02 @khatoni Can you take a look?

2023-04-24 17:23 UTC, khatoni requested changes

2023-04-24 17:23 UTC, khatoni commented on Seminars/Sem.07/Pract. 07/Task01/MyString.cpp
> +void MyString::free() {delete[] data;}
Inconsistent with brackets { }

2023-04-24 17:23 UTC, khatoni commented on Seminars/Sem.07/Pract. 07/Task01/MyString.cpp
> +const char* MyString::c_str() {
you do not change the object, so use const

2023-04-24 17:23 UTC, khatoni commented on Seminars/Sem.07/Pract. 07/Task01/MyString.h
> +    const char* c_str();
const

2023-04-24 17:23 UTC, khatoni commented on Seminars/Sem.07/Pract. 07/Task01/MyString.h
> +    char& operator[](size_t i) const;
no const here

2023-04-24 17:23 UTC, khatoni commented on Seminars/Sem.07/Pract. 07/Task01/MyString.h
> +    char operator[](size_t i);
const here

2023-04-24 17:23 UTC, khatoni commented on Seminars/Sem.07/Pract. 07/Task01/MyString.cpp
> +    return false;
return size==0

2023-04-24 17:23 UTC, khatoni commented on Seminars/Sem.07/Pract. 07/Task01/MyString.cpp
> +    return false;
one line

2023-04-24 17:23 UTC, khatoni commented on Seminars/Sem.07/Pract. 07/Task01/MyString.cpp
> +    return false;
one line

2023-04-24 17:23 UTC, khatoni commented on Seminars/Sem.07/Pract. 07/Task01/MyString.cpp
> +    char* str = new char[8];
why 8

2023-04-29 20:31 UTC, closed without merging