Pract.07 Add: 01 | Teodora Tsaneva
Justsvetoslavov/Object-oriented_programming_FMI pull request #165
Opened 2023-04-13 21:14 UTC by tedy11

Teodora Tsaneva
IS 4 5MI9700155

2023-04-17 15:15 UTC, Nedko-Nedev requested changes

2023-04-17 15:15 UTC, Nedko-Nedev commented on Seminars/Sem.07/Pract. 07/String.cpp
> +    data[strlen(other.data)] = '\0';
strcpy добавя терминиращата нула.

2023-04-17 15:15 UTC, Nedko-Nedev commented on Seminars/Sem.07/Pract. 07/String.cpp
> +    data = new char[strlen(other.data) + 1];
Помисли как може да си осигуриш strong exception safety.

2023-04-17 15:15 UTC, Nedko-Nedev commented on Seminars/Sem.07/Pract. 07/String.cpp
> +    return data[index];
Тук ти трябва проверка за индекс, дали index не е по-голям от размера на data.

2023-04-17 15:15 UTC, Nedko-Nedev commented on Seminars/Sem.07/Pract. 07/String.cpp
> +String String::append(const String& string) const
Този метод много прилича на един оператор, който си направила вече. Използвай този оператор, вместо да преписваш логиката.

2023-04-17 15:15 UTC, Nedko-Nedev commented on Seminars/Sem.07/Pract. 07/String.cpp
> +    String temp;
И този метод много прилича на вече написани неща в други оператори, преизползвай ги.
Няма нужда да слагаш терминираща 0 след strcpy.

2023-04-17 15:15 UTC, Nedko-Nedev commented on Seminars/Sem.07/Pract. 07/String.h
> +	friend std::ostream& operator<<(std::ostream& os, const String& string);
Помисли как можеш да имплементираш оператора за чете от поток.
Подсказка: Четенето може да става с цикъл, символ по символ, до достигане на края на потока, като всеки път "прибавяш" прочетеното към String параметъра.

2023-04-22 12:35 UTC, Justsvetoslavov commented
@Nedko-Nedev Changes have been committed. Can you review it again?

2023-04-23 18:02 UTC, Nedko-Nedev requested changes

2023-04-23 18:02 UTC, Nedko-Nedev commented on Seminars/Sem.07/Pract. 07/String.cpp
> +        return data[0];
Тук е добре да връщаш терминираща нула, виж документацията:
https://cplusplus.com/reference/string/string/operator[]/

2023-04-23 18:02 UTC, Nedko-Nedev commented on Seminars/Sem.07/Pract. 07/String.cpp
> +String String::append(const String& lhs, const String& rhs)
Помисли отново този метод. Както си го реализирала е член-функцията, тоест ще се изпълнява this.append( две неща). Струва ли ти се логично?

2023-04-23 18:02 UTC, Nedko-Nedev commented on Seminars/Sem.07/Pract. 07/String.cpp
> +        string[index] = c;
Как си сигурна, че string[index] е валиден индекс? Може да няма място в string обекта. По-скоро с някой метод, който добавя символ към низа и вътре в метода да се проверява за размера, потенциално да се оразмери при нужда.

2023-05-03 13:27 UTC, closed without merging