Pract07: Add 01 | Plamen Stoynev
Justsvetoslavov/Object-oriented_programming_FMI pull request #171
Opened 2023-04-19 17:59 UTC by plamenstoynev

Plamen Stoynev
IS 4 8MI0700195

2023-04-22 12:38 UTC, Justsvetoslavov commented
@Nedko-Nedev can you take a look(review it) ?

2023-04-23 17:53 UTC, Nedko-Nedev requested changes

2023-04-23 17:53 UTC, Nedko-Nedev commented on Seminars/Sem.07/Pract. 07/Task01/String.hpp
> +	String(String& other);
add const in the parameter type

2023-04-23 17:53 UTC, Nedko-Nedev commented on Seminars/Sem.07/Pract. 07/Task01/String.hpp
> +	String& operator=(String& other);
add const in the parameter type

2023-04-23 17:53 UTC, Nedko-Nedev commented on Seminars/Sem.07/Pract. 07/Task01/String.cpp
> +	size_t lengthOfOtherString = strlen(other.myStr) + 1;
Много сходен метод с горния, помисли как да отделиш общата логика.

2023-04-23 17:53 UTC, Nedko-Nedev commented on Seminars/Sem.07/Pract. 07/Task01/String.cpp
> +	strcpy(this->myStr, other.myStr);
Помисли как се реализира operator=, има си шаблонна процедура. Постарай се и да я разбираш.

2023-04-23 17:53 UTC, Nedko-Nedev commented on Seminars/Sem.07/Pract. 07/Task01/String.cpp
> +	temp.myStr = new char[newLength];
вместо temp можеш директно да използваш this, като преди това си осбоводил паметта от this.

2023-04-23 17:53 UTC, Nedko-Nedev commented on Seminars/Sem.07/Pract. 07/Task01/String.cpp
> +	return !(lStr < rStr);
!(lStr <= rStr)
Помисли защо.
Можеш също и rStr < lStr (просто да размениш аргументите)

2023-04-23 17:53 UTC, Nedko-Nedev commented on Seminars/Sem.07/Pract. 07/Task01/String.cpp
> +	return !(lStr >= rStr);
!(lstr > rStr) 
Помисли защо.
Може вместо това да използваш и горния оператор

2023-04-23 17:53 UTC, Nedko-Nedev commented on Seminars/Sem.07/Pract. 07/Task01/String.cpp
> +		os << string.myStr[indexHelper];
indexHelper++ в цикъла?

2023-04-23 17:53 UTC, Nedko-Nedev commented on Seminars/Sem.07/Pract. 07/Task01/String.cpp
> +// std::istream& operator>>(std::istream& is, const String& string)
Четеш от потока символ по символ до достигане на end of file.
Имаш метод append да добаяне в стринга.

2023-04-23 17:53 UTC, Nedko-Nedev commented on Seminars/Sem.07/Pract. 07/Task01/String.cpp
> +void String::setMyStr(const char* string)
Това не е желана функционалност. Имаш copy constructor и такъв с параметър.

2023-04-29 20:27 UTC, closed without merging