Pract.01: Add 07-08 | Nikita Beliy
Justsvetoslavov/Object-oriented_programming_FMI pull request #18
Opened 2023-02-25 23:41 UTC by N1k1ta-white

Nikita Beliy
SI 1 9MI800022

2023-02-28 10:53 UTC, khatoni requested changes

2023-02-28 10:53 UTC, khatoni commented on Task07.cpp
> +    char name[100];
It would be better to not use numbers. Instead use global constant like const int MAX_NAME_SIZE=100

2023-02-28 10:53 UTC, khatoni commented on Task07.cpp
> +enum Genre {
It would be better to use enum class

2023-02-28 10:53 UTC, khatoni commented on Task07.cpp
> +Movie add_movie(const char name[], int time, Genre gen, double rate) {
const int , const double , const Genre& gen

2023-02-28 10:53 UTC, khatoni commented on Task07.cpp
> +void sort_movies(Movie *movies, int num) {
const int num

2023-02-28 10:53 UTC, khatoni commented on Task08.cpp
> +    char name[30];
const int MAX_NAME_SIZE=30;
char name[MAX_NAME_SIZE+1];

2023-02-28 10:53 UTC, khatoni commented on Task08.cpp
> +        cin >> res.students[i].name;
This way you cannot enter first name and last name;
Use getline
When you enter from the console char* and then you want to enter number you need to use cin.ignore();

2023-02-28 10:53 UTC, khatoni commented on Task08.cpp
> +int how_many_students_get_money(const Group& group, double min_grade) {
const double min_grade

2023-02-28 10:53 UTC, khatoni commented on Task08.cpp
> +Group students_with_money(const Group& group, double min_grade) {
const double min_grade

2023-02-28 10:53 UTC, khatoni commented on Task08.cpp
> +    }
The task is to sort the students who will get scholarship

2023-03-04 22:51 UTC, Justsvetoslavov commented
Good solutions. Good job 👍

2023-03-04 22:51 UTC, closed without merging