Pract.01: Add 03-05 | Plamen Stoynev
Justsvetoslavov/Object-oriented_programming_FMI pull request #19
Opened 2023-02-26 11:58 UTC by plamenstoynev

Plamen Stoynev
IS 4 8MI0700195

2023-02-26 20:27 UTC, Nedko-Nedev requested changes

2023-02-26 20:27 UTC, Nedko-Nedev commented on Seminars/Sem.01/Pract.01/Task03.cpp
> +int** createMatrix(size_t rows, size_t cols)
Всяка глобална функция, която заделя динамична памет е отговорна за нейното освобождаване.
Причината е, че не знаем от кого може да бъде извикана тази функция и дали той ще се сети да си освободи паметта. Тоест, не може да разчитаме на това.

2023-02-26 20:27 UTC, Nedko-Nedev commented on Seminars/Sem.01/Pract.01/Task03.cpp
> +int main()
За тази задача е по-добре да заделяш и освобождаваш динамичната памет в main-а и да подаваш като аргумент на функция самата матрица, в която искаш да правиш промени.

2023-02-27 09:25 UTC, plamenstoynev commented on Seminars/Sem.01/Pract.01/Task03.cpp
> +int** createMatrix(size_t rows, size_t cols)
Функцията връща указател към заделената памет, чрез който да бъде освободена заделената памет вбъдеще. Нали всяка функция трябва да отговаря само за едно нещо, как се очаква тогава `createMatrix` да изпълнява фукнцията на `deleteMatrix`?

2023-03-01 15:04 UTC, Justsvetoslavov commented
See example solutions, where it can be easier (1 liners) and const correctness for task03.

2023-03-01 15:04 UTC, closed without merging