Pract.01: Add 04-06 | Nikita Beliy
Justsvetoslavov/Object-oriented_programming_FMI pull request #22
Opened 2023-02-26 23:37 UTC by N1k1ta-white

Nikita Beliy
SI 1 9MI800022

2023-02-27 19:29 UTC, khatoni requested changes

2023-02-27 19:29 UTC, khatoni commented on Task04.cpp
> +         << "Fac. number: " << student.fac_num << endl;
The name of the function suggest that you will initialise student, instead you are printing it.

2023-02-27 19:29 UTC, khatoni commented on Task04.cpp
> +void change_info(Student& student, const char name[], int fac_num) {
const int fac_num

2023-02-27 19:29 UTC, khatoni commented on Task05.cpp
> +void read_complex_num(const Complex_num &num) {
again the name is ambiguous

2023-02-27 19:29 UTC, khatoni commented on Task06.cpp
> +void read_point(const Point &p) {
I suggest  void print(const Point& p) , because read_point may refer to reading the point from the console

2023-02-27 19:29 UTC, khatoni commented on Task06.cpp
> +bool in_circle(const Point& p, int r) {
const int r

2023-03-01 14:59 UTC, Justsvetoslavov commented
Check example solutions.

2023-03-01 14:59 UTC, closed without merging