Pract.01 Add 01-03 | Velislava Veneva
Justsvetoslavov/Object-oriented_programming_FMI pull request #26
Opened 2023-02-27 16:15 UTC by velislavav

Velislava Veneva
SI 1 5MI0600243

2023-02-27 17:51 UTC, GeorgiTerziev02 requested changes
Overall good but you have some minor issues like missing consts, please see the comments.

2023-02-27 17:51 UTC, GeorgiTerziev02 commented on Seminars/Sem.01/Pract.01/Task01.cpp
> +int lowerNumByPointer(int* num1, int* num2)
const int*

2023-02-27 17:51 UTC, GeorgiTerziev02 commented on Seminars/Sem.01/Pract.01/Task02.cpp
> +void inputArr(int* arr, const int& SIZE)
We do not put & on primitive types

2023-02-27 17:51 UTC, GeorgiTerziev02 commented on Seminars/Sem.01/Pract.01/Task02.cpp
> +int countBiggerSymbols(int* arr, const int& SIZE, const char symbol)
const int*, because we do not change it, also remove &

2023-02-27 17:51 UTC, GeorgiTerziev02 commented on Seminars/Sem.01/Pract.01/Task02.cpp
> +		if (arr[i] > symbol - '0')
We do not need - '0' in this task

2023-02-27 17:51 UTC, GeorgiTerziev02 commented on Seminars/Sem.01/Pract.01/Task03.cpp
> +int** transposeMatrix(int** matrix, const int rows, const int cols)
const int** matrix - because we do not change it

2023-02-27 17:51 UTC, GeorgiTerziev02 commented on Seminars/Sem.01/Pract.01/Task03.cpp
> +void printMatrix(int** matrix, const int rows, const int cols)
const int** - because we do not change it

2023-02-28 08:55 UTC, GeorgiTerziev02 approved these changes

2023-03-01 14:59 UTC, Justsvetoslavov commented
Unable to cherry-pick due to error. (is branch deleted or corrupted?)
In any case, kudos 👏

2023-03-01 14:59 UTC, closed without merging