Pract.01: Add 04-06 | Martin Gatev
Justsvetoslavov/Object-oriented_programming_FMI pull request #30
Opened 2023-02-27 22:44 UTC by MGatev

Martin Gatev
SI 1 0MI0600143

2023-02-28 11:20 UTC, khatoni requested changes

2023-02-28 11:20 UTC, khatoni commented on Seminars/Sem.01/Pract.01/Martin Gatev/Task04.cpp
> +	char name[MAX_SIZE_NAME];
Alignment??

2023-02-28 11:20 UTC, khatoni commented on Seminars/Sem.01/Pract.01/Martin Gatev/Task06.cpp
> +	if (distanceFromCenterToPoint - radius <= 0.00001)
please do not use just numbers, write global constant epsilon

2023-02-28 11:20 UTC, khatoni commented on Seminars/Sem.01/Pract.01/Martin Gatev/Task06.cpp
> +	}
You can combine this if and the last statement and just use one line ternary operator

2023-03-01 15:12 UTC, Justsvetoslavov requested changes

2023-03-01 15:12 UTC, Justsvetoslavov commented on Seminars/Sem.01/Pract.01/Martin Gatev/Task04.cpp
> +const int MAX_SIZE_NAME = 31;
30 , not 31

2023-03-01 15:12 UTC, Justsvetoslavov commented on Seminars/Sem.01/Pract.01/Martin Gatev/Task05.cpp
> +ComplexNumber sumOfComplexNumbers(const ComplexNumber& number1,
format?

2023-03-01 15:12 UTC, Justsvetoslavov commented on Seminars/Sem.01/Pract.01/Martin Gatev/Task05.cpp
> +	return sum;
1 liner

2023-03-01 15:12 UTC, closed without merging