Pract.02: Add 01-03 | Nikita Beliy
Justsvetoslavov/Object-oriented_programming_FMI pull request #50
Opened 2023-03-01 21:22 UTC by N1k1ta-white

Nikita Beliy
SI 1 9MI800022

2023-03-06 20:03 UTC, khatoni requested changes

2023-03-06 20:03 UTC, khatoni commented on Task01.cpp
> +    int sum, comp;
Check whether the file has opened successfully

2023-03-06 20:03 UTC, khatoni commented on Task02.cpp
> +    while(read_file >> std::noskipws >> rotator)
You are not allowed to use std::noskipws

2023-03-06 20:03 UTC, khatoni commented on Task03.cpp
> +    while (file >> std::noskipws >> rotator) {
What is std::noskipws?

2023-03-06 20:03 UTC, khatoni commented on Task03.cpp
> +            switch (line) {
Read again the task, you can not be sure that they will be in this order!

2023-03-06 20:03 UTC, khatoni commented on Task03.cpp
> +            }
Same as in the function above

2023-03-12 22:58 UTC, Justsvetoslavov commented
Check uploaded solutions.
You can re-open the PR or open a new one if you have better solution or questions.

2023-03-12 22:58 UTC, closed without merging