Pract.01: Add 07-08| Gabriela Mladenova
Justsvetoslavov/Object-oriented_programming_FMI pull request #53
Opened 2023-03-01 22:55 UTC by gabrielavm

Gabriela Mladenova
SI 1 3MI0600225

2023-03-02 14:59 UTC, khatoni requested changes

2023-03-02 14:59 UTC, khatoni commented on Seminars/Sem.01/Pract.01/Task07.cpp
> +enum MovieGenre
Use enum class

2023-03-02 14:59 UTC, khatoni commented on Seminars/Sem.01/Pract.01/Task07.cpp
> +};
Leave empty lines after structures and functions

2023-03-02 14:59 UTC, khatoni commented on Seminars/Sem.01/Pract.01/Task07.cpp
> +};
Leave empty line

2023-03-02 14:59 UTC, khatoni commented on Seminars/Sem.01/Pract.01/Task07.cpp
> +
It would be better to use switch case

2023-03-02 14:59 UTC, khatoni commented on Seminars/Sem.01/Pract.01/Task07.cpp
> +}
empty line

2023-03-02 14:59 UTC, khatoni commented on Seminars/Sem.01/Pract.01/Task07.cpp
> +    }
Just write cout<<movies[topMovieIndex].movieName<<" "<<movies[topMovieIndex].duration and so on.
This for loop is useless

2023-03-02 14:59 UTC, khatoni commented on Seminars/Sem.01/Pract.01/Task07.cpp
> +}
empty line

2023-03-02 14:59 UTC, khatoni commented on Seminars/Sem.01/Pract.01/Task07.cpp
> +}
empty line

2023-03-02 14:59 UTC, khatoni commented on Seminars/Sem.01/Pract.01/Task07.cpp
> +        }
This sorting algorithm is not working. It is wrong(see your nested for loop)
And can you think of algorithm which will be better in this situation.

2023-03-02 14:59 UTC, khatoni commented on Seminars/Sem.01/Pract.01/Task08.cpp
> +        ++counter;
inputStudentInfo(group.studentList[i]);

2023-03-02 14:59 UTC, khatoni commented on Seminars/Sem.01/Pract.01/Task08.cpp
> +    group.averageGrade = sumOfGrades / counter;
This counter is useless, you can use numberOfStudents

2023-03-02 14:59 UTC, khatoni commented on Seminars/Sem.01/Pract.01/Task08.cpp
> +}
empty line

2023-03-02 14:59 UTC, khatoni commented on Seminars/Sem.01/Pract.01/Task08.cpp
> +    }
empty line after loops

2023-03-02 14:59 UTC, khatoni commented on Seminars/Sem.01/Pract.01/Task08.cpp
> +}
empty line

2023-03-02 14:59 UTC, khatoni commented on Seminars/Sem.01/Pract.01/Task08.cpp
> +void printScholarshipsList(const Group& group, const double minGrade, Student* student)
What is Student* student?

2023-03-04 22:50 UTC, Justsvetoslavov commented
Good solutions. Good job 👍

2023-03-04 22:50 UTC, closed without merging