Pract.02: Add 01-03 | Ivan Angelov
Justsvetoslavov/Object-oriented_programming_FMI pull request #59
Opened 2023-03-02 21:29 UTC by ivan9643

Ivan Angelov 
SI 5 9MI0600190

2023-03-03 23:49 UTC, GeorgiTerziev02 requested changes

2023-03-03 23:49 UTC, GeorgiTerziev02 commented on Seminars/Sem.02/Pract.02/Task01.cpp
> +		char buffer[128];
use constant

2023-03-03 23:49 UTC, GeorgiTerziev02 commented on Seminars/Sem.02/Pract.02/Task01.cpp
> +		cout << buffer << endl;
Please check again what is required in the task

2023-03-03 23:49 UTC, GeorgiTerziev02 commented on Seminars/Sem.02/Pract.02/Task02.cpp
> +}
use tellg, seekg

2023-03-03 23:49 UTC, GeorgiTerziev02 commented on Seminars/Sem.02/Pract.02/Task03.cpp
> +void PrintLines(char** lines, size_t linesCount) {
const

2023-03-03 23:49 UTC, GeorgiTerziev02 commented on Seminars/Sem.02/Pract.02/Task03.cpp
> +void CharArrayCopy(char* toCopy, size_t length,char* copyTo) {
const

2023-03-03 23:49 UTC, GeorgiTerziev02 commented on Seminars/Sem.02/Pract.02/template.txt
> +Dear, {title} {recipient_name}.
do not upload txt

2023-03-12 22:58 UTC, Justsvetoslavov commented
Check uploaded solutions.
You can re-open the PR or open a new one if you have better solution or questions.

2023-03-12 22:58 UTC, closed without merging