Pract.02: Add 04-07 | Nikita Beliy
Justsvetoslavov/Object-oriented_programming_FMI pull request #64
Opened 2023-03-03 18:51 UTC by N1k1ta-white

Nikita Beliy
SI 1 9MI800022

2023-03-06 20:39 UTC, khatoni requested changes

2023-03-06 20:39 UTC, khatoni commented on Task04.cpp
> +Pair createPair(const int &a = 0, const int &b = 0) {
do not use & with primitive data types!

2023-03-06 20:39 UTC, khatoni commented on Task04.cpp
> +void initPair(Pair &pair, const int &a, const int &b) {
why & with int

2023-03-06 20:39 UTC, khatoni commented on Task04.cpp
> +Pair readPairFromFile(std::fstream &file, const int &mode = 0) {
const int

2023-03-06 20:39 UTC, khatoni commented on Task04.cpp
> +    return res;
you can just write
int a; int b;
file>>a>>b

2023-03-06 20:39 UTC, khatoni commented on Task06.cpp
> +    while (me >> std::noskipws >> reader)
std::noskipws??

2023-03-06 20:39 UTC, khatoni commented on Task07.cpp
> +User readUserFromFile(std::fstream &file, const int &mode = 0) {
again int &, why

2023-03-06 20:39 UTC, khatoni commented on Task07.cpp
> +    return true;
if the strings are with different sizes

2023-03-12 22:58 UTC, Justsvetoslavov commented
Check uploaded solutions.
You can re-open the PR or open a new one if you have better solution or questions.

2023-03-12 22:58 UTC, closed without merging