Pract.02: Add | Plamen Stoynev
Justsvetoslavov/Object-oriented_programming_FMI pull request #67
Opened 2023-03-04 13:08 UTC by plamenstoynev

Plamen Stoynev
IS 4 8MI0700195

2023-03-06 16:39 UTC, GeorgiTerziev02 requested changes

2023-03-06 16:39 UTC, GeorgiTerziev02 commented on Seminars/Sem.02/Pract.02/Task02.cpp
> +}
There is easier way

2023-03-06 16:39 UTC, GeorgiTerziev02 commented on Seminars/Sem.02/Pract.02/Task03.cpp
> +#include <iostream>
Check what is required in the task again!

2023-03-12 22:58 UTC, Justsvetoslavov commented
Check uploaded solutions.
You can re-open the PR or open a new one if you have better solution or questions.

2023-03-12 22:58 UTC, closed without merging