Pract.02: Add 04-07 | Kiril Georgiev
Justsvetoslavov/Object-oriented_programming_FMI pull request #68
Opened 2023-03-04 13:35 UTC by KirilGeorgiev247

Kiril Georgiev
SI 1 8MI0600268

2023-03-06 19:54 UTC, khatoni requested changes

2023-03-06 19:54 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task04.cpp
> +void convertStringToInt(const char* str, int& num, const int numLength)
Do not use & with primitive data types

2023-03-06 19:54 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task04.cpp
> +	file.seekg(prevPos);
You have written so many redundant lines of code 
As I can see the way you are writing to the file you can just write
while(!file.eof()){
int a, b;
file>>a>>b;
pair.a=a'
pair.b=b;

2023-03-06 19:54 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +bool compareStrings(const char* firstString, const char* secondString)
what happens when secondString size is less than the size of firstString

2023-03-06 19:54 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +	char* password = new char[USER_PROPERTY_MAX_LENGTH];
You do not free the allocated memory

2023-03-06 19:54 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task04.cpp
> +	return &pair;
BIG mistake. If this was at the exam, you would receive 0 points for the whole exam.

2023-03-06 19:54 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task04.cpp
> +	Pair pair1 = *CreatePair(4, 6);
big mistake

2023-03-06 20:31 UTC, khatoni requested changes

2023-03-06 20:31 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +	}
You do not free the dynamic memory in system

2023-03-12 22:59 UTC, Justsvetoslavov commented
Check uploaded solutions.
You can re-open the PR or open a new one if you have better solution or questions.

2023-03-12 22:59 UTC, closed without merging