Pract.02: Add 01-03 | Vasil Paligorov
Justsvetoslavov/Object-oriented_programming_FMI pull request #70
Opened 2023-03-04 15:11 UTC by VasilPaligorov

Vasil Paligorov
IS 4 06MI0700192

2023-03-07 18:04 UTC, Nedko-Nedev requested changes

2023-03-07 18:04 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task02.cpp
> +int lengthOfFile(ifstream &file) {
Може да стане без обхождане на файла. Помисли в насока файлови указатели.

2023-03-07 18:04 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task03.cpp
> +void getValuesFromFile(ifstream &valuesFile, char values[][max_line_length]) {
Не е казано, че шаблоните ще са точно title, recipient_name, message, sender_name. 
Те просто се четат от файл във формат:
< key1 > < value1 >
< key2 > < value2 >
.....

2023-03-12 22:58 UTC, Justsvetoslavov commented
Check uploaded solutions.
You can re-open the PR or open a new one if you have better solution or questions.

2023-03-12 22:58 UTC, closed without merging