Pract.02: Add 01-03 | Borislav Gunovski
Justsvetoslavov/Object-oriented_programming_FMI pull request #80
Opened 2023-03-05 22:59 UTC by IHaveNoIdeaWhatImDo-ing

Borislav Gunovski
IS 4 1MI0700119

2023-03-07 20:00 UTC, Nedko-Nedev requested changes

2023-03-07 20:00 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task02.cpp
> +    while (fileReader.is_open() && !fileReader.eof())
Има по-лесен начин за намиране на големината на файл. Помисли в посока файлови указатели.

2023-03-07 20:00 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task03.cpp
> +	streamWriter << "Dear, " << elements[0] << " " << elements[1] << ".\n" << '\n' << elements[2] << '\n' << '\n' << "Sincirely,\n" << elements[3];
Идеята е, че и двата файла, които се четат имат почти произволно съдържание и се очаква решението също да работи за най-различни файлове, не само за примерния.
Със сигурност на същите шаблони, които са използвани в единия файл, ще бъдат дадени конкретни стойности в другия. Прави се mapping по ключ и стойност.

2023-03-12 23:05 UTC, Justsvetoslavov commented
Check uploaded solutions.
You can re-open the PR or open a new one if you have better solution or questions.

2023-03-12 23:05 UTC, closed without merging