Pract.02: Add 04-06 | Borislav Gunovski
Justsvetoslavov/Object-oriented_programming_FMI pull request #81
Opened 2023-03-05 22:59 UTC by IHaveNoIdeaWhatImDo-ing

Borislav Gunovski
IS 4 1MI0700119

2023-03-07 20:33 UTC, Nedko-Nedev requested changes

2023-03-07 20:33 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task04.cpp
> +		rel.pairs[i] = rels[i];
Слагай скоби дори на едноредовките, подобрява четимостта.

2023-03-07 20:33 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task04.cpp
> +Pair initPair(void)
Това с  (void)  е по-скоро C стил, не C++, в смисъл че не е необходимо, когато функцията не приема аргументи. Просто () върши работа, за разлика от същия синтаксис в C.

2023-03-07 20:33 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task04.cpp
> +		rel.pairs[rel.size] = pair;
Тук трябва да ползваш скоби, защото така както си го написал дори и rel.size >= MAX_PAIRS, пак ще се увеличи.
Като цяло ползвай скоби, иначе стават точно такива грешки.

2023-03-07 20:33 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task04.cpp
> +}
Не затваряш потока.

2023-03-07 20:33 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task04.cpp
> +	copyElements(rel, pairs, i - 1);
Не затваряш входния поток.

2023-03-07 20:33 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task04.cpp
> +	ifstream streamReader(ofpath);
Хубаво е да проверяваш дали файлът може да се отвори.

2023-03-07 20:33 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task06.cpp
> +bool strComp(char* str1, char* str2, int amount)
Използвай готовите методи от библиотеките. За дължината също.

2023-03-07 20:33 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task06.cpp
> +		 password[MAX_SIZE],
Слагай тип на всяко поле, не така с изброяване. Подобрява четимостта.

2023-03-07 20:33 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task06.cpp
> +void saveSys(System& sys, bool overwrite)
Тук за какво ти е втория аргумент?

2023-03-07 20:33 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task06.cpp
> +		sys.users[i++] = user;
Валидирай, че няма да препълниш масива от структурата.

2023-03-07 20:33 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task06.cpp
> +			for (int j = 0; j < sus.entries && !flag; ++j)
Можеш да отделиш for-а във функция, която да ти връща true/false дали може да се логне user-a.

2023-03-12 23:05 UTC, Justsvetoslavov commented
Check uploaded solutions.
You can re-open the PR or open a new one if you have better solution or questions.

2023-03-12 23:05 UTC, closed without merging