Pract.02: Add 07 | Borislav Gunovski
Justsvetoslavov/Object-oriented_programming_FMI pull request #82
Opened 2023-03-05 22:59 UTC by IHaveNoIdeaWhatImDo-ing

Borislav Gunovski
IS 4 1MI0700119

2023-03-11 20:04 UTC, Nedko-Nedev requested changes

2023-03-11 20:04 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +	short category;
Използвай директно Category като тип.

2023-03-11 20:04 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +void strCopy(char arr[MAX_SIZE], string& str)
Използвай вградените функции за всички подобни операции с низове.

2023-03-11 20:04 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +enum Category { OKN, M, PM, PR, Other };
Хубаво е да имаш enum и за вида на изпита.

2023-03-11 20:04 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +		  MAX_DISCIPLINES = 100;
Декларирай всяка променлива със собствен тип, не така с изреждане. Подобрява четимостта.

2023-03-11 20:04 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +	int end = 0;
Къде ползваш така променлива?

2023-03-11 20:04 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +	for (int i = 0; i < MAX_DISCIPLINES; ++i)
Не трябва ли да проверяваш по броя на записание дисциплини, не по максималния брой?

2023-03-11 20:04 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +void saveDiscipline(Subject& sub, Subject subs[MAX_DISCIPLINES])
Няма нужда да подаваш размера, компилаторът автоматично го конвертира до Subject *.
Важи за повечето функции в програмата.

2023-03-11 20:04 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +short shortFromString(string& str)
Защо са ти тези методи и защо ползваш string?

2023-03-11 20:04 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +		getline(str, temp, ',');
Няма нужда да четеш всичко като string и после да го конвертираш, можеш да четеш и целочислените типове.
Потокът ще спре, когато срещне символ, различен от число. Ще изпадне в състояние fail, после може да го върнеш в състояние good и да продължиш четенето.

2023-03-11 20:04 UTC, Nedko-Nedev commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +int main()
Може да направиш потребителски интерфейс, който да работи с командите. 
Покажи с тестове, че методите и програмата като цяло работи.

2023-03-12 23:05 UTC, Justsvetoslavov commented
Check uploaded solutions.
You can re-open the PR or open a new one if you have better solution or questions.

2023-03-12 23:05 UTC, closed without merging