Pract.02: Add 01-02 | Tsvetelina Gotsova
Justsvetoslavov/Object-oriented_programming_FMI pull request #84
Opened 2023-03-06 17:52 UTC by tsvetellina5

Tsvetelina Gotsova 
SI 2 6MI0600033

2023-03-06 20:05 UTC, khatoni requested changes

2023-03-06 20:05 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task01.cpp
> +}
Use functions, also you have to read the sum and the product later. Read the task again!

2023-03-06 20:05 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task02.cpp
> +	std::ifstream file(name);
You should save the initial position of get pointer

2023-03-12 23:11 UTC, Justsvetoslavov commented
Check uploaded solutions.
You can re-open the PR or open a new one if you have better solution or questions.

2023-03-12 23:11 UTC, closed without merging