Pract.02: Add 01 02 06 | Teodora Tsaneva
Justsvetoslavov/Object-oriented_programming_FMI pull request #90
Opened 2023-03-06 20:00 UTC by tedy11

Teodora Tsaneva
IS 4 5MI0700155

2023-03-06 20:10 UTC, khatoni requested changes

2023-03-06 20:10 UTC, khatoni commented on Task01.cpp
> +    readFile.close();
You should have function one for reading and one for writing, both with is open check

2023-03-06 20:10 UTC, khatoni commented on file_Task02.txt
> +sdjfhj
Do not upload .txt files!

2023-03-06 20:10 UTC, khatoni commented on file_Task06.txt
> +    printFile << endl;
You do not need another stream

2023-03-06 20:10 UTC, khatoni commented on file_Task06.txt
> +    myFile.getline(bufer, 1024);
1024 should be const variable

2023-03-06 20:10 UTC, khatoni commented on file_Task06.txt
> +        break;
this should be the condition in the while loop

2023-03-06 20:10 UTC, khatoni commented on Task06.cpp
> +﻿#include <iostream>
Sorry, the comment are in the .txt file :D

2023-03-06 20:10 UTC, khatoni commented on Task02.cpp
> +            i++;
Use tellg, seekg

2023-03-12 23:12 UTC, Justsvetoslavov commented
Check uploaded solutions.
You can re-open the PR or open a new one if you have better solution or questions.

2023-03-12 23:12 UTC, closed without merging