Pract.02 add 01-03 | Gabriela Mladenova
Justsvetoslavov/Object-oriented_programming_FMI pull request #93
Opened 2023-03-06 20:47 UTC by gabrielavm

Gabriela Mladenova
SI 1 3MI0600225

2023-03-06 20:54 UTC, khatoni requested changes

2023-03-06 20:54 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task01.cpp
> +int readFromFile(const char NAME[], int &substract)
do not use & with primitive data types

2023-03-06 20:54 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task02.cpp
> +
Save the initial position of tellg, in order not to change the position of tellg when finding the length of the file

2023-03-06 20:54 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task03.cpp
> +}
Read the task again

2023-03-12 23:11 UTC, Justsvetoslavov commented
Check uploaded solutions.
You can re-open the PR or open a new one if you have better solution or questions.

2023-03-12 23:11 UTC, closed without merging