Pract.02 : Add 04-07 | Gabriela Mladenova
Justsvetoslavov/Object-oriented_programming_FMI pull request #94
Opened 2023-03-06 20:52 UTC by gabrielavm

Gabriela Mladenova
SI 1 3MI0600225

2023-03-09 13:46 UTC, khatoni requested changes

2023-03-09 13:46 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task04.cpp
> +void addPairToRelation(Relation& newRelation, Pair& newPair)
const Pair&

2023-03-09 13:46 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task04.cpp
> +Relation readPairFromFile()
this name is ambiguos
You read a relation from the file in this funciton

2023-03-09 13:46 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +const char FILENAME1[] = "usersList.txt";
FILENAME1 is not good name

2023-03-09 13:46 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +    newSystem.countOfStudentsInSystem = i;
The idea is to store the current number of users in countOfStudentsInSystem, not the maximum possible size

2023-03-09 13:46 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +    std::cout << "You are successfully registered!" << std::endl;
What is the logic here???

2023-03-09 13:46 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +int strCompare(char str1[], char str2[])
use const

2023-03-09 13:46 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +    }
just if(str[i]!=str2[i]) break;

2023-03-09 13:46 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +void logInTheSystem(System& newSystem)
const

2023-03-12 23:13 UTC, Justsvetoslavov commented
@khatoni Review the PR again.
Specifically interested in Task07 as the current one has flaws.

2023-03-16 13:31 UTC, khatoni requested changes
I think that your idea behind the functions printUsersList ,inputUsers and makeRegistration is not clear enough. Please chech the uploaded solution for this task.

2023-03-16 13:31 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +
Again why you want to read the maximum number of students. What will happen when you try to read from the file the maximum possible size of students and the file has less users saved in it.

2023-03-16 13:31 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task07.cpp
>  void inputUsers(System &newSystem)
I do not understand the logic here. As I can see, you want to save the whole system to file, therefore you do not change it. Why do you change the countOfStudents . Re-think the logic here. Why the for cycle is looping to the maximum possible number of users. It should be to the current number of users in the system

2023-03-16 13:31 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +    std::cin >> newSystem.systemOfUsers[0].name;
Why do you store the name of the new user at index 0

2023-03-16 13:31 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task07.cpp
> +    std::cin >> newSystem.systemOfUsers[1].email;
Why do you store the email of the new user at index 1, which is different index from index 0

2023-03-16 13:31 UTC, khatoni commented on Seminars/Sem.02/Pract.02/Task07.cpp
>      return 0;
You can just write:  return str1[i]==str2[i]

2023-03-16 22:44 UTC, closed without merging